# Generated by Django 4.1 on 2022-08-31 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_resume_aboutwork_alter_resume_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobNotifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobTitle', models.CharField(max_length=255)),
                ('dateAdded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobReceived',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobTitle', models.CharField(max_length=255)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
