# Generated by Django 4.1 on 2022-09-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobnotifications_jobreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
