# Generated by Django 4.1 on 2022-09-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resume_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pics/'),
        ),
    ]
