# Generated by Django 4.1 on 2022-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_resume_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
